"""Adjust schema based on user feedback

Revision ID: 56a76034006a
Revises: f8de344a765a
Create Date: 2026-07-16 12:20:14.792716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56a76034006a'
down_revision: Union[str, None] = 'f8de344a765a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraint first to avoid dependent objects drop error
    op.drop_constraint('general_journal_lines_header_id_fkey', 'general_journal_lines', type_='foreignkey')
    
    op.create_table('general_journal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_general_journal_headers_entry_number', table_name='general_journal_headers')
    op.drop_table('general_journal_headers')
    op.drop_index('ix_library_files_user_id', table_name='library_files')
    op.drop_table('library_files')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.add_column('documents', sa.Column('created_by', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('is_vouchers', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('voucher_type', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('general_journal_lines', sa.Column('general_journal_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'general_journal_lines', 'general_journal', ['general_journal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('general_journal_lines', 'header_id')
    op.drop_column('general_journal_lines', 'description')
    sa_inventory_type = sa.Numeric(precision=10, scale=2)
    op.add_column('inventory', sa.Column('purchase_price', sa_inventory_type, nullable=False))
    op.drop_index('ix_inventory_sku', table_name='inventory')
    op.drop_column('inventory', 'sku')
    op.add_column('messages', sa.Column('source', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'source')
    op.add_column('inventory', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index('ix_inventory_sku', 'inventory', ['sku'], unique=True)
    op.drop_column('inventory', 'purchase_price')
    op.add_column('general_journal_lines', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('general_journal_lines', sa.Column('header_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'general_journal_lines', type_='foreignkey')
    op.create_foreign_key('general_journal_lines_header_id_fkey', 'general_journal_lines', 'general_journal_headers', ['header_id'], ['id'], ondelete='CASCADE')
    op.drop_column('general_journal_lines', 'general_journal_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'voucher_type')
    op.drop_column('documents', 'is_vouchers')
    op.drop_column('documents', 'created_by')
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name='invoices_partner_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey')
    )
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_table('library_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='library_files_pkey')
    )
    op.create_index('ix_library_files_user_id', 'library_files', ['user_id'], unique=False)
    op.create_table('general_journal_headers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='general_journal_headers_pkey')
    )
    op.create_index('ix_general_journal_headers_entry_number', 'general_journal_headers', ['entry_number'], unique=True)
    op.drop_table('users')
    op.drop_table('general_journal')
    # ### end Alembic commands ###
