"""Major schema refactor v2

Revision ID: 94175f7b93a6
Revises: 56a76034006a
Create Date: 2026-07-17 04:06:23.485053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94175f7b93a6'
down_revision: Union[str, None] = '56a76034006a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('raw_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_plans_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('thought', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('action_input', sa.Text(), nullable=True),
    sa.Column('action_output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_plans_id'], ['agent_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chunks', sa.Column('rag_document_id', sa.Uuid(), nullable=False))
    op.drop_constraint('chunks_document_id_fkey', 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'rag_documents', ['rag_document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chunks', 'document_id')
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('source_url', sa.String(length=1024), nullable=True))
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'is_vouchers')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'voucher_type')
    op.add_column('general_journal', sa.Column('vouchers_id', sa.Uuid(), nullable=True))
    op.add_column('general_journal', sa.Column('storage_url', sa.String(length=1024), nullable=True))
    op.add_column('general_journal', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('general_journal', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'general_journal', 'vouchers', ['vouchers_id'], ['id'], ondelete='SET NULL')
    op.drop_column('general_journal', 'source')
    op.add_column('inventory', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('documents_source_url', sa.String(length=1024), nullable=True))
    op.add_column('messages', sa.Column('vouchers_source_url', sa.String(length=1024), nullable=True))
    op.drop_column('messages', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('messages', 'vouchers_source_url')
    op.drop_column('messages', 'documents_source_url')
    op.drop_column('messages', 'status')
    op.drop_column('inventory', 'unit')
    op.add_column('general_journal', sa.Column('source', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'general_journal', type_='foreignkey')
    op.drop_column('general_journal', 'approved_at')
    op.drop_column('general_journal', 'status')
    op.drop_column('general_journal', 'storage_url')
    op.drop_column('general_journal', 'vouchers_id')
    op.add_column('documents', sa.Column('voucher_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('is_vouchers', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_name')
    op.drop_column('conversations', 'summary')
    op.add_column('chunks', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key('chunks_document_id_fkey', 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chunks', 'rag_document_id')
    op.drop_table('agent_tasks')
    op.drop_table('agent_plans')
    op.drop_table('vouchers')
    op.drop_table('rag_documents')
    # ### end Alembic commands ###
