"""add_file_modified_at_to_rag_document

Revision ID: e76843c933a9
Revises: f97394d3a2c2
Create Date: 2026-07-17 09:17:00.951192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76843c933a9'
down_revision: Union[str, None] = 'f97394d3a2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_documents', sa.Column('file_modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_documents', 'file_modified_at')
    # ### end Alembic commands ###
